#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ToneCategory {
    Observation,
    Refinement,
    Resolution,
    Blocking,
    Praise,
    ReviewRequest,
    NoAction,
    ReviewerAssigned,
    ObserveOpened,
    ObservePassed,
    ObserveBlocked,
    ObserveDraft,
    RiskLow,
    RiskMedium,
    RiskHigh,
    DescriptionMissing,
    DescriptionTemplateOnly,
    PipelinePaused,
    RefineReady,
}
